ERROR 2013-11-18 19:25:25,576 middleware 3907 139816229582592 Uncaught exception: 'dict' object has no attribute 'url_domain'
Traceback (most recent call last):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/views/profile.py", line 74, in profile
    'ncns': get_ncns(emp),
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/services/jobs_list.py", line 76, in get_ncns
    q = Q(domain_domain=url.url_domain, domain_suffix=url.url_suffix)
AttributeError: 'dict' object has no attribute 'url_domain'
