ERROR 2013-11-21 07:11:52,687 middleware 32463 140364046534400 Uncaught exception: Import by filename is not supported.
Traceback (most recent call last):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/views/profile.py", line 79, in profile
    'employer_names_top_cities_jobs': names_and_top_cities_for_employer(emp),
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/services/jobs_list.py", line 70, in names_and_top_cities_for_employer
    top_cities_jobs = top_cities_for_company(ncn)
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/services/jobs_list.py", line 58, in top_cities_for_company
    serp_url = reverse('jobs-url:jobs-query', 'c-'+c+'/l-'+l) #'http://www.simplyhired.com/a/jobs/list/c-%s/l-%s' % (
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/urlresolvers.py", line 467, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/urlresolvers.py", line 311, in app_dict
    self._populate()
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/urlresolvers.py", line 263, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: Import by filename is not supported.
