ERROR 2013-11-15 21:16:41,182 speed_logging_utils 31833 140640690747168 browser speed log HTTP request keys missing from JSON object
None
ERROR 2013-11-15 21:16:41,506 speed_logging_utils 31833 140640690747168 browser speed log HTTP request keys missing from JSON object
None
ERROR 2013-11-15 21:16:41,617 speed_logging_utils 31833 140640690747168 browser speed log HTTP request JSON parse failed
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 93, in read_browser_speed_data
    speed_data = json.loads(request.body)
  File "/usr/lib64/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 360, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 378, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR 2013-11-15 21:16:41,805 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (django_begins)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
AttributeError: 'Request' object has no attribute 'speed'
ERROR 2013-11-15 21:16:41,944 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (php_bridge_begins)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
AttributeError: 'Request' object has no attribute 'speed'
ERROR 2013-11-15 21:16:42,087 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (django_begins)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
KeyError: 'django_begins'
ERROR 2013-11-15 21:16:42,216 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (php_bridge_begins)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
KeyError: 'php_bridge_begins'
ERROR 2013-11-15 21:16:42,343 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (django_begins)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
AttributeError: 'Request' object has no attribute 'speed'
ERROR 2013-11-15 21:16:42,489 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (django_ends)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
AttributeError: 'Request' object has no attribute 'speed'
ERROR 2013-11-15 21:16:42,623 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (php_bridge_begins)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
AttributeError: 'Request' object has no attribute 'speed'
ERROR 2013-11-15 21:16:42,758 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (php_bridge_ends)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
AttributeError: 'Request' object has no attribute 'speed'
ERROR 2013-11-15 21:16:42,893 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (php_bridge_begins)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
KeyError: 'php_bridge_begins'
ERROR 2013-11-15 21:16:43,018 speed_logging_utils 31833 140640690747168 unable to retrieve timestamp from request object for speed logging (php_bridge_ends)
Traceback (most recent call last):
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/lib/speed_logging_utils.py", line 35, in read
    value = request.speed[name]
KeyError: 'php_bridge_ends'
ERROR 2013-11-15 21:27:21,468 middleware 32377 140260358010624 Uncaught exception: (1049, "Unknown database 'articles'")
Traceback (most recent call last):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/oleg/code/web-serpng/code/serpng/articles/views/index.py", line 19, in index
    for cat in categories:
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/query.py", line 123, in _result_iter
    self._fill_cache()
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/query.py", line 939, in _fill_cache
    self._result_cache.append(next(self._iter))
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/query.py", line 344, in _safe_iterator
    for item in iterator:
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 839, in execute_sql
    cursor = self.connection.cursor()
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/backends/__init__.py", line 324, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 405, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1049, "Unknown database 'articles'")
ERROR 2013-11-15 21:59:43,142 middleware 408 140130342930176 Uncaught exception: 'QuerySet' object has no attribute 'url_domain'
Traceback (most recent call last):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/views/profile.py", line 74, in profile
    'ncns': get_ncns(emp),
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/services/jobs_list.py", line 73, in get_ncns
    ncns.append(ws.url_domain + ws.url_suffix)
AttributeError: 'QuerySet' object has no attribute 'url_domain'
